server: server.c ../utils/sendfile2.c ../utils/error_handler.c ../utils/logger.c ../utils/sockets.c
	gcc -o server server.c ../utils/sendfile2.c ../utils/error_handler.c ../utils/logger.c ../utils/sockets.c
